name: Docker Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Java 21 for Maven tests
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      # Run Maven tests
      - name: Run Tests
        run: mvn test

      # Build Docker image
      - name: Build Docker image
        run: docker-compose build
